# ********************************************************************************
# FileName     : copy-to-public-repository.yml
# Description  : private repository의 파일을 public repository로 복사
#                소스를 숨기고 배포할 파일만 공개
# Author       : SCS
# Created Date : 2024.07.22
# Reference    : 
# Modified     :  
# ********************************************************************************

name: Copy to Destination Public Repository

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
  DEST_REPO_URL: "github.com/etboard/ETboard_Public_Data.git"
  DEST_PATH: "resources/firmware/arduino/Kit_SmartSchool_IoT"
on:
  push:
    branches: [ main ]  # 또는 원하는 브랜치
  workflow_dispatch:  # 수동 트리거 옵션

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Copy file to destination repo
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        # start
        echo ">> start workflows"        
        git config --global user.name 'ketri3000'
        git config --global user.email 'ketri3000@gmail.com'
        echo ""        
        echo ">> step1000: current folder and list file"        
        pwd
        ls
        
        # clone
        echo ""        
        echo ">> step1100: clone dest repository "        
        git clone https://$DEST_REPO_URL dest
        echo "echo step 2000: current folder and list file"        
        pwd
        ls

        # copy ; 이 아래 부분만 수정하면 됩
        echo ""        
        echo "echo step3000: copy file "        
        mkdir -p dest/$DEST_PATH
        cp src/arduino/Kit_SmartSchool_Iot/Kit_SmartSchool_IoT.ET-Board.bin dest/$DEST_PATH

        # push
        cd dest
        git add .
        git commit -m "Deploy executable from src_repo to public repo"
        git push https://$PAT@$DEST_REPO_URL

# ********************************************************************************
# End of File
# ********************************************************************************
